# Generated by Django 3.2.4 on 2021-06-24 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210624_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested',
            field=models.ManyToManyField(blank=True, related_name='interested_participants', to=settings.AUTH_USER_MODEL, verbose_name='Заинтересованные сотрудники'),
        ),
    ]
