# Generated by Django 3.2.4 on 2021-06-23 13:18

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название события')),
                ('date', models.DateField(verbose_name='Дата начала события')),
            ],
        ),
        migrations.CreateModel(
            name='MentorGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=64, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254)),
                ('interested', models.ManyToManyField(blank=True, related_name='interested_participants', to=settings.AUTH_USER_MODEL, verbose_name='Заинтересованные сотрудники')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название статуса')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название потока')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='event_stats_app.event', verbose_name='Событие')),
                ('interested', models.ManyToManyField(blank=True, related_name='interested_tracks', to=settings.AUTH_USER_MODEL, verbose_name='Заинтересованные сотрудники')),
            ],
        ),
        migrations.CreateModel(
            name='TrackUserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_stats_app.participant')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_stats_app.participantstatus')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_stats_app.track')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tracks', through='event_stats_app.TrackUserStatus', to='event_stats_app.Participant', verbose_name='Участники трэка'),
        ),
    ]
