# Generated by Django 3.2.4 on 2021-06-30 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название события')),
                ('date', models.DateField(verbose_name='Дата начала события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название потока')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='event_stats_app.event', verbose_name='Событие')),
                ('interested', models.ManyToManyField(blank=True, related_name='interested_tracks', to=settings.AUTH_USER_MODEL, verbose_name='Заинтересованные сотрудники')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
            },
        ),
        migrations.CreateModel(
            name='TrackChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='Последнее время изменения')),
                ('task_url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на тестовое задание')),
                ('status', models.CharField(choices=[('Зарегистрировался', 'Registered'), ('На проверке', 'On Review'), ('Принят', 'Accepted'), ('Не принят', 'Denied')], default='Зарегистрировался', max_length=32, verbose_name='Статус участника')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_stats_app.track', verbose_name='Выбранный трек')),
            ],
            options={
                'verbose_name': 'Выбор трека',
                'verbose_name_plural': 'Выбор треков',
            },
        ),
        migrations.AddField(
            model_name='track',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tracks', through='event_stats_app.TrackChoice', to=settings.AUTH_USER_MODEL, verbose_name='Участники трэка'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Отзыв')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Последние изменения')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('participant_track_choice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='event_stats_app.trackchoice', verbose_name='Выбор трека участником')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ревьювер')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
