# Generated by Django 3.2.4 on 2021-06-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_stats_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorGroup',
        ),
    ]
