# Generated by Django 3.2.4 on 2021-06-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_stats_app', '0002_delete_mentorgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='interested',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='middle_name',
        ),
    ]
