# Generated by Django 3.2.4 on 2021-06-24 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_stats_app', '0003_auto_20210624_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tracks', through='event_stats_app.TrackUserStatus', to=settings.AUTH_USER_MODEL, verbose_name='Участники трэка'),
        ),
        migrations.AlterField(
            model_name='trackuserstatus',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
