# Generated by Django 3.2.4 on 2021-06-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_stats_app', '0004_auto_20210624_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackuserstatus',
            name='status',
            field=models.CharField(choices=[('Зарегистрировался', 'Registered'), ('На проверке', 'On Review'), ('Принят', 'Accepted'), ('Не принят', 'Denied')], default='Зарегистрировался', max_length=32),
        ),
        migrations.DeleteModel(
            name='ParticipantStatus',
        ),
    ]
