# Generated by Django 3.2.4 on 2021-06-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_stats_app', '0005_auto_20210624_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='name',
            new_name='title',
        ),
    ]
