# Generated by Django 3.2.4 on 2021-06-24 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_stats_app', '0006_auto_20210624_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Зарегистрировался', 'Registered'), ('На проверке', 'On Review'), ('Принят', 'Accepted'), ('Не принят', 'Denied')], default='Зарегистрировался', max_length=32)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_stats_app.feedback')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_stats_app.track')),
            ],
        ),
        migrations.DeleteModel(
            name='TrackUserStatus',
        ),
        migrations.AlterField(
            model_name='track',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tracks', through='event_stats_app.TrackChoice', to=settings.AUTH_USER_MODEL, verbose_name='Участники трэка'),
        ),
    ]
