# Generated by Django 3.2.4 on 2021-06-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_stats_app', '0007_auto_20210624_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackchoice',
            name='feedback',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event_stats_app.feedback'),
        ),
    ]
