# Generated by Django 3.2.4 on 2021-06-24 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_stats_app', '0008_alter_trackchoice_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackchoice',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='participant_track_choice',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='event_stats_app.trackchoice'),
            preserve_default=False,
        ),
    ]
