# Generated by Django 3.2.4 on 2021-06-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_stats_app', '0009_auto_20210624_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
            preserve_default=False,
        ),
    ]
