# Generated by Django 3.2.4 on 2021-06-26 06:41

from django.db import migrations
from event_stats_app.models import Group


def append_group(apps, schema_editor):
    groups = (
        {"title": "Администраторы трека", "description": "В этой группе состоят Администраторы трека"},
        {"title": "Группа 2", "description": "В этой группе состоят не Администраторы трека"},
    )
    for group in groups:
        model = Group(title = group["title"], description = group["description"])
        model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('event_stats_app', '0011_auto_20210626_1138'),
    ]

    operations = [
        migrations.RunPython(append_group),
    ]
