# Generated by Django 3.2.4 on 2021-06-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_stats_app', '0012_auto_20210626_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='mentorgroup',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterModelOptions(
            name='trackchoice',
            options={'verbose_name': 'Выбор трека', 'verbose_name_plural': 'Выбор треков'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='MentorGroup',
        ),
    ]
