# Generated by Django 3.2.4 on 2021-06-26 12:46

from django.db import migrations
from django.contrib.auth.models import Group


def append_group(apps, schema_editor):
    groups = (
        {"name": "Администратор"},
        {"name": "Ментор"},
        {"name": "Участник"},
    )
    for group in groups:
        # model = Group(**group)
        obj, created = Group.objects.get_or_create(name=group["name"])
        if created:
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('event_stats_app', '0013_auto_20210626_1438'),
    ]

    operations = [
        migrations.RunPython(append_group),
    ]
