# Generated by Django 3.2.4 on 2021-06-26 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_stats_app', '0014_auto_20210626_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Последние изменения'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='participant_track_choice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='event_stats_app.trackchoice', verbose_name='Выбор трека участником'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ревьювер'),
        ),
        migrations.AlterField(
            model_name='trackchoice',
            name='change_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее время изменения'),
        ),
        migrations.AlterField(
            model_name='trackchoice',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='trackchoice',
            name='status',
            field=models.CharField(choices=[('Зарегистрировался', 'Registered'), ('На проверке', 'On Review'), ('Принят', 'Accepted'), ('Не принят', 'Denied')], default='Зарегистрировался', max_length=32, verbose_name='Статус участника'),
        ),
        migrations.AlterField(
            model_name='trackchoice',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_stats_app.track', verbose_name='Выбранный трек'),
        ),
    ]
