# Generated by Django 3.2.4 on 2021-06-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_stats_app', '0015_auto_20210626_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackchoice',
            name='task_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на тестовое задание'),
        ),
    ]
