# Generated by Django 3.2.4 on 2021-06-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_stats_app', '0016_trackchoice_task_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackchoice',
            name='task_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на тестовое задание'),
        ),
    ]
